services:
  database:
    image: postgres:latest
    container_name: database
    # ports:
    #   - 5432:5432
    env_file:
      - data-service/.env
    networks:
      - hyper-network
    volumes:
      - /tmp/db-data:/var/lib/postgresql/data
    restart: on-failure

  migration:
    image: python:3.12-slim
    container_name: migration
    env_file:
      - data-service/.env
    networks:
      - hyper-network
    volumes:
      - ./db-migrations:/tmp/db
    depends_on:
      - database
    command: ["sh", "-c", "/tmp/db/init.sh"]
    restart: "no"

  data-service:
    build: ./data-service
    image: data-service
    container_name: data-service
    volumes:
      - ./data-service:/app
      - ./grpc:/grpc
    depends_on:
      - migration
    networks:
      - hyper-network
    restart: always

  gateway:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hyper-network
    ports:
      - 80:80
    restart: always
  
  auth-service:
    build: ./auth-service
    image: auth-service
    container_name: auth-service
    volumes:
      - ./auth-service:/app
      - ./grpc:/grpc
    # ports:
    #   - 8000:8000
    env_file:
      - ./auth-service/.env
    networks:
      - hyper-network
    depends_on:
      - migration
    restart: on-failure

  user-service:
    build: ./user-service
    image: user-service
    container_name: user-service
    volumes:
      - ./user-service:/app
      - ./grpc:/grpc
    # ports:
    #   - 8001:8000
    env_file:
      - ./user-service/.env
    networks:
      - hyper-network
    depends_on:
      - migration
    restart: on-failure

networks:
  hyper-network:
    driver: bridge
    name: hyper-network