services:
  database:
    image: postgres:latest
    container_name: hyperdb
    ports:
      - 5433:5432
    env_file:
      - .env
    # volumes:
    #   - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - hyper-network
    restart: on-failure

  auth-service:
    build: .
    image: auth-service
    container_name: auth-service
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - hyper-network
    depends_on:
      - database
    restart: on-failure

networks:
  hyper-network:
    driver: bridge
    name: hyper-network